### ISSUE TITLE
Starting point of progress

### ISSUE THREAD

**Issue by matviishyn** [RobertFOConnor/react-native-progress-wheel#5]
Is there a way to customize the starting point of progress? Now it starts only from the right side

Also would be nice to have a property to set `backgroundWidth`

**Comment by kvrscream** [comment]
Hi. Does exist some exhibition a percent value?
Thanks

**Comment by RobertFOConnor** [comment]
If you want to change the starting position, you can simply wrap the component in a transformed view.
E.g. In your styles set transform: [{rotate: '180deg'}] to start from the left side.

**Comment by VivekVithlani** [comment]
Can you please add some code for example?

**Comment by thorakmedichi** [comment]
I tried to rotate the progress so that it starts at the top using the following code:

```js
     <View style={{ transform: [{ rotate: '270deg' }] }}>
            <AnimatedProgressWheel
                size={30}
                width={4}
                progress={progress}
                color={palette.primary_300}
                backgroundColor={palette.grey_700}
            />
        </View>
```

The issue is that when doing this inner circle seems misplaced within the outer circle causing the progress wheel to look thinner on one side than on the other. Any suggestions?

![Screenshot_20210329_094448](https://user-images.githubusercontent.com/5092843/112870897-8e6bcb80-9073-11eb-956b-c3d6b7d9ba8a.png)
